# Generated by Django 3.2 on 2022-04-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
