# Generated by Django 3.2 on 2022-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='Display',
            field=models.BooleanField(default=False),
        ),
    ]
