# Generated by Django 3.2 on 2022-04-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magician', '0003_remove_performer_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='image',
        ),
    ]
